<!DOCTYPE html>
<html>
    <head>
    	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    	<?php echo $this->partial("layouts/header") ?>
        <title>Phalcon PHP Framework</title>
    </head>
    <body>
    	<div id="navbar">
    	<?php echo $this->partial("layouts/navbar") ?>
    	</div>

    	<div id="container">
        <?php echo $this->getContent() ?>
        </div>

        <div id="foot">
        <?php echo  $this->partial("layouts/footer") ?>
        </div>
    </body>
</html>
